### ISSUE TITLE
네비게이션바 화면 전환 버그

### ISSUE THREAD

**Issue by real-future** [Direchan/SleepWellApp#31]
# 버그 내용 : 
네비게이션바 작동에 이상이 있음

### 버그 재현 과정 : 
처음 버튼을 눌렀을 때는 잘 동작하지만, 페이지를 이동하고 버튼을 다시 눌렀을 때는 창이 열리지 않음.

### 예상 동작(본래 의도하려던 바) : 
각 페이지에서 버튼이 동작해야함.
다른 페이지로 넘어가서 버튼을 눌러도 동작해야함.

# 스크린샷
![Simulator Screen Recording - iPhone 14 Pro - 2023-09-07 at 20 16 07](https://github.com/Direchan/SleepWellApp/assets/85066307/19db1abf-67ba-423f-a95a-bb8432eddb9f)

**Comment by Direchan** [comment]
본래 viewDidLoad 에 추가되던

NavigationUtil.currentViewController = self
NavigationUtil.setupNavigationBar(for: self)
해당 코드를 
viewWillAppear 에 이동하여 해결
