### ISSUE TITLE
API 조회수 호출 이슈

### ISSUE THREAD

**Issue by Direchan** [Direchan/SleepWellApp#57]
# 버그 내용 :
조회수 호출 간헐적? 실패 현상

### 버그 재현 과정 : 

10개의 영상 정보를 불러온다고 가정했을 시, 2~3개는 조회수 정보가 누락됨

### 예상 동작(본래 의도하려던 바) : 

셀 및 디테일페이지 내부에서도 조회수가 정확히 출력되어야 함

### 실제 동작(버그 상황) : 

스크린샷참고

# 스크린샷

![simulator_screenshot_06742395-B4E5-4244-B4DD-01D230778ACE](https://github.com/Direchan/SleepWellApp/assets/100069134/d22716e4-1a4f-43d2-a211-199defc0d3d4)

![simulator_screenshot_844AF4A4-EFF4-4EA4-9169-EE6786103CD9](https://github.com/Direchan/SleepWellApp/assets/100069134/480f66ac-2e72-439e-a4b8-fd98bd6b19f5)

**Comment by real-future** [comment]
문제상황 : 기존 코드에서는 contentDetails와 statistics의 API호출을 따로 하고 있음. 이런 비동기 호출 때문에 뭐가 먼저 실행될지 모르며, 실행되는 해당 정보만 먼저 반영이 됨. 

해결 방법 : 따라서 아래처럼 동기화를 통해 contentDetails와 statistics의 정보를 모두 받은 후에 completion을 호출할 수 있도록 수정하였음.
